# https://hub.docker.com/_/python
FROM python:3.8.15-slim

# Allow statements and log messages to immediately appear in the Knative logs
ENV PYTHONUNBUFFERED True

ENV APP_HOME /app
WORKDIR $APP_HOME

COPY ./requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . ./

ENV PORT 8080

EXPOSE $PORT

CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 300 main:app
